# Generated by Django 5.1 on 2024-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ingrediente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bebida",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
