# Generated by Django 5.1 on 2024-08-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bebida"),
    ]

    operations = [
        migrations.AddField(
            model_name="bebida",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bebidas",
                to="core.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bebida",
            name="ingredientes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bebidas",
                to="core.ingrediente",
            ),
        ),
        migrations.AddField(
            model_name="bebida",
            name="isbn",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bebida",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="bebida",
            name="quantidade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
