# Generated by Django 5.1 on 2024-08-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bebida_categoria_bebida_ingredientes_bebida_isbn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bebida",
            name="isbn",
        ),
        migrations.CreateModel(
            name="Comida",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ("quantidade", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comidas",
                        to="core.categoria",
                    ),
                ),
                (
                    "ingredientes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comidas",
                        to="core.ingrediente",
                    ),
                ),
            ],
        ),
    ]
