# Generated by Django 5.1 on 2024-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_bebida_categoria_remove_bebida_ingredientes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="ingredientes",
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ManyToManyField(blank=True, related_name="produtos", to="core.categoria"),
        ),
        migrations.AddField(
            model_name="produto",
            name="ingredientes",
            field=models.ManyToManyField(blank=True, null=True, related_name="produtos", to="core.ingrediente"),
        ),
    ]
