# Generated by Django 5.1 on 2024-09-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_produto_categoria_remove_produto_ingredientes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itenscompra",
            name="bebida",
        ),
    ]
