# Generated by Django 5.1 on 2024-09-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_itenscompra_bebida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="core.produto"
            ),
        ),
    ]
