# Generated by Django 5.1.1 on 2024-09-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_itenscompra_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="ingredientes",
            field=models.ManyToManyField(blank=True, related_name="produtos", to="core.ingrediente"),
        ),
    ]
