# Generated by Django 5.1.1 on 2024-09-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_produto_imagemdoproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenscompra",
            name="produto",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.produto"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itenscompra",
            name="compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="core.compra"
            ),
        ),
    ]
