# Generated by Django 5.1.1 on 2024-09-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_itenscompra_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="observacoes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
