# Generated by Django 5.1.1 on 2024-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_itenscompra_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="status",
            field=models.IntegerField(choices=[(1, "Em Estoque"), (2, "Poucas Unidades"), (3, "Em Falta")], default=1),
        ),
    ]
