# Generated by Django 5.1.1 on 2024-10-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_user_cep_alter_user_cpf_alter_user_idade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
