# Generated by Django 5.1.1 on 2024-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_descrição_produto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Em Estoque"), (2, "Poucas Unidades (Próximo à 100 unidades)"), (3, "Em Falta")], default=1
            ),
        ),
    ]
